### ISSUE TITLE
fix travis CI build test fail

### ISSUE THREAD

**Issue by HyunmoAhn** [AhKi/oh-my-desk#63]
https://travis-ci.org/AhKi/oh-my-desk/builds/339783427?utm_source=github_status&utm_medium=notification

```
Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
    at new GitHubPublisher (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-publish/src/gitHubPublisher.ts:54:15)
    at createPublisher (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder-lib/src/publish/PublishManager.ts:235:14)
    at PublishManager.getOrCreatePublisher (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder-lib/src/publish/PublishManager.ts:160:19)
    at PublishManager.scheduleUpload (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder-lib/src/publish/PublishManager.ts:111:28)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder-lib/src/publish/PublishManager.ts:101:14)
    at EventEmitter.emit (events.js:165:20)
    at Packager.dispatchArtifactCreated (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder-lib/src/packager.ts:214:23)
    at /home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder-lib/src/publish/updateInfoBuilder.ts:190:14
    at Generator.next (<anonymous>)
From previous event:
    at default.map (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder-lib/out/publish/updateInfoBuilder.js:163:30)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at /home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder-lib/src/publish/updateInfoBuilder.ts:186:25
    at Generator.next (<anonymous>)
From previous event:
    at writeUpdateInfoFiles (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder-lib/out/publish/updateInfoBuilder.js:169:22)
    at /home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder-lib/src/publish/PublishManager.ts:180:11
From previous event:
    at PublishManager.awaitTasks (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder-lib/out/publish/PublishManager.js:436:11)
    at /home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder/src/builder.ts:294:32
    at /home/travis/build/AhKi/oh-my-desk/node_modules/builder-util/src/promise.ts:26:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at executeFinally (/home/travis/build/AhKi/oh-my-desk/node_modules/builder-util/out/promise.js:37:21)
    at /home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder/src/builder.ts:287:10
    at Generator.next (<anonymous>)
From previous event:
    at _build (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder/src/builder.ts:257:10)
    at then (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at Object.args [as handler] (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/home/travis/build/AhKi/oh-my-desk/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/home/travis/build/AhKi/oh-my-desk/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/home/travis/build/AhKi/oh-my-desk/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/travis/build/AhKi/oh-my-desk/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn build" exited with 1.


```

**Comment by HyunmoAhn** [comment]
when add Circle CI, we don't need travis CI.

But above error is occured in CircleCI when running build process.
So fix above issue in Circle CI
